Add helm chart and skaffold.yaml
rayyanqcri/rayyan-dedup pull request #13
Opened 2020-09-17 12:07 UTC by fabubaker

2020-09-17 15:59 UTC, hammady requested changes

2020-09-17 15:59 UTC, hammady commented on helm/rayyan-dedup/values.yaml
> +    tolerations: &WORKER_TOLERATIONS
Tolerations are now part of rayyanlib templates.

2020-09-17 15:59 UTC, hammady commented on README.md
>  # rayyan-dedup
Please insert a build badge here: create the pipeline, run and test it on the branch, then from the drop down get its badge markdown after setting branch to mater and scope to the Build stage.

2020-09-20 11:10 UTC, fabubaker commented on README.md
>  # rayyan-dedup
Done

2020-09-20 11:10 UTC, fabubaker commented on helm/rayyan-dedup/values.yaml
> +    tolerations: &WORKER_TOLERATIONS
Removed `WORKER_TOLERATIONS`

2020-09-20 11:23 UTC, hammady commented on README.md
>  # rayyan-dedup
To be consistent, I am trying to rename the pipeline to just `rayyan-dedup` then we have to update the badge. The rename is not working for some reason.

2020-09-20 11:24 UTC, hammady commented on README.md
>  # rayyan-dedup
Also you didn't scope it to the build stage!

2020-09-20 11:24 UTC, hammady commented on helm/rayyan-dedup/values.yaml
> +    tolerations:
Remove the tolerations block completely!

2020-09-20 13:36 UTC, fabubaker commented on helm/rayyan-dedup/values.yaml
> +    tolerations:
Wait, I don't understand, where else would you specify tolerations?

2020-09-20 13:38 UTC, fabubaker commented on README.md
>  # rayyan-dedup
There was no option to scope to the build stage!

2020-09-20 13:46 UTC, fabubaker commented on README.md
>  # rayyan-dedup
I manually edited the URL and set it to Build.

2020-09-20 13:51 UTC, fabubaker commented on README.md
>  # rayyan-dedup
> To be consistent, I am trying to rename the pipeline to just `rayyan-dedup` then we have to update the badge. The rename is not working for some reason.

I renamed the pipeline and updated the badge link.

2020-09-20 14:07 UTC, hammady commented on README.md
>  # rayyan-dedup
I am not sure why no more scopes appear, same for the new scaltainer pipeline as well. I checked rayyancore pipeline though and it has all scopes. But observe the badge itself it says "never built"!

<img width="626" alt="image" src="https://user-images.githubusercontent.com/855847/93713307-99ddb780-fb63-11ea-8076-d4e4a57d0fee.png">

2020-09-20 14:08 UTC, hammady approved these changes

2020-09-20 14:08 UTC, merged